{
  parserClass="io.github.marksosman.dddcontextmapper.parser.CmlParser"
  parserUtilClass="com.intellij.lang.parser.GeneratedParserUtilBase"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Cml"
  psiImplClassSuffix="Impl"
  psiPackage="io.github.marksosman.dddcontextmapper.psi"
  psiImplPackage="io.github.marksosman.dddcontextmapper.psi.impl"

  elementTypeHolderClass="io.github.marksosman.dddcontextmapper.psi.CmlTypes"
  elementTypeClass="io.github.marksosman.dddcontextmapper.psi.CmlElementType"
  tokenTypeClass="io.github.marksosman.dddcontextmapper.CmlTokenType"

  tokens=[
    KW_CONTEXT_MAP     = "ContextMap"
    KW_BOUNDED_CONTEXT = "BoundedContext"
    KW_DOMAIN          = "Domain"
    KW_SUBDOMAIN       = "Subdomain"
    KW_CONTAINS        = "contains"
    KW_IMPLEMENTS      = "implements"
    KW_REFINES         = "refines"
    KW_REALIZES        = "realizes"
    KW_SUPPORTS        = "supports"

    DECL_KEYWORD  = "DECL_KEYWORD"
    PROP_KEYWORD  = "PROP_KEYWORD"
    FLOW_KEYWORD  = "FLOW_KEYWORD"
    STORY_KEYWORD = "STORY_KEYWORD"
    PRIMITIVE     = "PRIMITIVE"
    CONSTANT      = "CONSTANT"

    LBRACE   = "{"
    RBRACE   = "}"
    LBRACKET = "["
    RBRACKET = "]"
    LPAREN   = "("
    RPAREN   = ")"
    LANGLE   = "<"
    RANGLE   = ">"
    EQ       = "="
    COMMA    = ","
    SEMI     = ";"
    COLON    = ":"
    DCOLON   = "::"
    MINUS    = "-"
    AT       = "@"
    PLUS     = "+"
    STAR     = "*"

    BIARROW  = "<->"
    RARROW   = "->"
    LARROW   = "<-"

    IDENTIFIER   = "regexp:[A-Za-z_][A-Za-z0-9_]*"
    STRING       = "regexp:\"[^\"]*\""
    NUMBER       = "regexp:[0-9]+(\.[0-9]+)?"
    LINE_COMMENT = "regexp://[^\r\n]*"
    BLOCK_COMMENT= "regexp:/\*([^*]|\*[^/])*\*/"
  ]
}

cmlFile ::= item_*

private item_ ::= contextMap | boundedContext | domain | subdomain | nestedBlock

private name_ ::= IDENTIFIER | CONSTANT

// Context Map

contextMap ::= KW_CONTEXT_MAP name_? LBRACE contextMapEntry* RBRACE {
  pin=1
}

private contextMapEntry ::= containsStatement | relationship | property

containsStatement ::= KW_CONTAINS contextRef (COMMA contextRef)* { pin=1 }

relationship ::= contextRef roleList? arrow roleList? contextRef

roleList ::= LBRACKET role (COMMA role)* RBRACKET { pin=1 }

role ::= CONSTANT | IDENTIFIER

private arrow ::= BIARROW | RARROW | LARROW

// Bounded Context

boundedContext ::= KW_BOUNDED_CONTEXT name_ contextHeader_* LBRACE bodyEntry_* RBRACE {
  pin=1
}

private contextHeader_ ::= implementsClause | refinesClause | realizesClause

private implementsClause ::= KW_IMPLEMENTS domainRef (COMMA domainRef)* { pin=1 }

private refinesClause ::= KW_REFINES contextRef { pin=1 }

private realizesClause ::= KW_REALIZES contextRef (COMMA contextRef)* { pin=1 }

domain ::= KW_DOMAIN name_ LBRACE domainEntry_* RBRACE {
  pin=1
}

private domainEntry_ ::= subdomain | bodyEntry_

subdomain ::= KW_SUBDOMAIN name_ supportsClause? LBRACE bodyEntry_* RBRACE {
  pin=1
}

private supportsClause ::= KW_SUPPORTS name_ (COMMA name_)* { pin=1 }

private bodyEntry_ ::= nestedBlock | property | opaque_

nestedBlock ::= DECL_KEYWORD name_? nestedBody_? { pin=1 }

private nestedBody_ ::= LBRACE bodyEntry_* RBRACE

private opaque_ ::= IDENTIFIER | PROP_KEYWORD | FLOW_KEYWORD | STORY_KEYWORD
                  | PRIMITIVE | CONSTANT | STRING | NUMBER | DECL_KEYWORD
                  | LBRACKET | RBRACKET | LPAREN | RPAREN | LANGLE | RANGLE
                  | EQ | COMMA | SEMI | COLON | DCOLON | MINUS | AT | PLUS | STAR
                  | BIARROW | RARROW | LARROW
                  | KW_IMPLEMENTS | KW_REFINES | KW_REALIZES | KW_SUPPORTS | KW_CONTAINS

// Shared

property ::= propertyName EQ? propertyValue (COMMA propertyValue)*

propertyName ::= PROP_KEYWORD | IDENTIFIER

private propertyValue ::= STRING | NUMBER | CONSTANT | IDENTIFIER

contextRef ::= IDENTIFIER | CONSTANT

domainRef ::= IDENTIFIER | CONSTANT
